[package]
name = "sugarloaf-ffi-ios"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["staticlib"]

[dependencies]
sugarloaf = { path = "../sugarloaf", default-features = false, features = ["render"] }
terminal-core = { path = "../terminal-core", default-features = false }
raw-window-handle = { workspace = true }
skia-safe = { version = "0.93.1", features = ["metal", "textlayout"] }
