// MCP Router Core - FFI Header
// Auto-generated by cbindgen, do not edit manually

#ifndef MCP_ROUTER_CORE_H
#define MCP_ROUTER_CORE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to the router
 */
typedef struct McpRouterHandle McpRouterHandle;

/**
 * Result type for FFI operations
 */
typedef struct FfiResult {
  bool success;
  char *error_message;
} FfiResult;

/**
 * Create a new router instance
 */
struct McpRouterHandle *mcp_router_create(void);

/**
 * Destroy the router instance
 */
void mcp_router_destroy(struct McpRouterHandle *handle);

/**
 * Free a result's error message
 */
void mcp_router_free_result(struct FfiResult result);

/**
 * Free a string returned by the library
 */
void mcp_router_free_string(char *s);

/**
 * Add an HTTP server configuration
 * Returns a result indicating success or failure
 */
struct FfiResult mcp_router_add_http_server(struct McpRouterHandle *handle,
                                            const char *name,
                                            const char *url,
                                            const char *description);

/**
 * Add a stdio server configuration (JSON format)
 */
struct FfiResult mcp_router_add_server_json(struct McpRouterHandle *handle, const char *json);

/**
 * Load servers from JSON array
 */
struct FfiResult mcp_router_load_servers_json(struct McpRouterHandle *handle, const char *json);

/**
 * Load workspaces from JSON array
 */
struct FfiResult mcp_router_load_workspaces_json(struct McpRouterHandle *handle, const char *json);

/**
 * List all servers as JSON array
 */
char *mcp_router_list_servers(struct McpRouterHandle *handle);

/**
 * Remove a server by name
 */
struct FfiResult mcp_router_remove_server(struct McpRouterHandle *handle, const char *name);

/**
 * Set server enabled/disabled
 */
struct FfiResult mcp_router_set_server_enabled(struct McpRouterHandle *handle,
                                               const char *name,
                                               bool enabled);

/**
 * Set server flatten mode
 */
struct FfiResult mcp_router_set_server_flatten_mode(struct McpRouterHandle *handle,
                                                    const char *name,
                                                    bool flatten);

/**
 * Set expose management tools (Light/Full mode)
 * - false = Light mode (basic tools only)
 * - true = Full mode (includes add_server, remove_server, update_server)
 */
struct FfiResult mcp_router_set_expose_management_tools(struct McpRouterHandle *handle,
                                                         bool expose);

/**
 * Get current expose management tools setting
 */
bool mcp_router_get_expose_management_tools(struct McpRouterHandle *handle);

/**
 * Get router status as JSON
 */
char *mcp_router_get_status(struct McpRouterHandle *handle);

/**
 * Start the HTTP server
 */
struct FfiResult mcp_router_start_server(struct McpRouterHandle *handle, uint16_t port);

/**
 * Stop the HTTP server
 */
struct FfiResult mcp_router_stop_server(struct McpRouterHandle *handle);

/**
 * Initialize logging (call once at startup)
 */
void mcp_router_init_logging(void);

/**
 * Get version string
 */
char *mcp_router_version(void);

#endif  /* MCP_ROUTER_CORE_H */
